spring.application.name=Product-API


spring.datasource.url=jdbc:mysql://localhost:3306/mainproject
spring.datasource.username=root
spring.datasource.password=Snickers@001

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
